name: plugandplay
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluid_bottom_nav_bar: ^1.4.0
  flutter_rating_bar: ^4.0.1
  camera: ^0.10.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  flutter_slidable: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/

